### ISSUE TITLE
How to setup different php-versions for different sites?

### ISSUE THREAD

**Issue by xViBlackx** [rlerdorf/php7dev#38]
Hi,
i found your repository by searching for some vagrant box, which let me switch php-versions on one server. The reason why i need this: i want to setup a local dev box which can display different websites with different php versions and configurations.
I need to add the ioncube and zendguard_loader extensions for each php-version and it would be perfectly if i can switch the php-versions from sites via the .htaccess or configure it in the vhost file.

For example:
I have one Page www.example.com needs php5.3 and another www.example2.com needs php5.4. It can also be more than two sites.

Is there a known way how i can achieve this?
I would be grateful for help!

**Comment by ghost** [comment]
I notice that the path to the 'socket' is at /var/run/php-fpm.sock.

How about a setup like this:
/var/run/php53-fpm.sock
/var/run/php54-fpm.sock
/var/run/php55-fpm.sock
/var/run/php56-fpm.sock

I don't know enough about php and how it has implemented fastcgi to find where the current setting can be changed (to serve php as cgi at another .sock)

How can this be done?

**Comment by rlerdorf** [comment]
In the /etc/init.d/php53-fpm script you will find this line:

```
 php_fpm_CONF=${prefix}/etc/php-fpm.conf
```

$prefix is /usr/local and if you look at the bottom of /usr/local/etc/php-fpm.conf you will see it loads the pool info from 
/usr/local/etc/php-fpm.d/*.conf

And if you look in /usr/local/etc/php-fpm.d/www.conf you will see a listen line that says /var/run/php-fpm.sock

So, what you need to do if you want separate instances of php-fpm all running currently listening on different sockets is to edit each of the /etc/init.d/php*-fpm files and point them to separate /usr/local/etc/php-fpm.conf config files which in turn will point to separate /usr/local/etc/php-fpm.d directories and inside each of these define separate listen sockets.

I am not going to do this in this image because the main point of this image is to test the same site across different versions, so it is easier if there is just a single pool directory that will be used as you switch versions. But it shouldn't be all that hard to make the config file changes as I describe to achieve what you need.

**Comment by ghost** [comment]
Thanks!
- I copied the folder and the .conf file
- I edited the conf file to load configs from the new directory
- I renamed the socket in the new www.conf file 
- and I copied /etc/init.d/php56-fpm to php5-fpm
- I modified the path to the config file in the service to the new php5-fpm.conf

When I run  "sudo service php5-fpm start", I get this error:

```
Failed to start php5-fpm.service: Unit php5-fpm.service failed to load: No such file or directory.
```

**Comment by ghost** [comment]
when i enter
`sudo update-rc.d php5-fpm defaults`
it says
`insserv: script php56-fpm: service php56-fpm already provided!`

**Comment by ghost** [comment]
On the top of the file I found this (I think it is called LSB header)

```
### BEGIN INIT INFO
# Provides:          php56-fpm
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php56-fpm
# Description:       starts the PHP FastCGI Process Manager daemon
### END INIT INFO
```

I changed the references to the old service file and now it works!
Thanks voor your suggestion, sorry about my messing with service files :-)
