### ISSUE TITLE
Where is php-fpm log file? Or how to activate it? Does PHP7 log errors?

### ISSUE THREAD

**Issue by ianldgs** [rlerdorf/php7dev#48]

**Comment by ianldgs** [comment]
I was able to activate it, if anyone needs, just follow these steps:

1: edit:
`sudo vim /usr/local/etc/php-fpm.d/www.conf`

2: add to the end of the file:

``` sh
catch_workers_output = yes

php_flag[display_errors] = on
php_admin_value[error_log] = /var/log/fpm-php.www.log
php_admin_flag[log_errors] = on
```

3: create the log file, so php-fpm can write on it:
`touch /var/log/fpm-php.www.log && chmod 666 /var/log/fpm-php.www.log`

---

and then you can see all errors/warnings/etc using:
`tail -f /var/log/fpm-php.www.log`

**Comment by rlerdorf** [comment]
You should only need to turn log_errors on. Then it will go to the default error logging file. For nginx it would be /var/log/nginx/default-error.log

I have now turned on log_errors in the latest image.

**Comment by jessuppi** [comment]
Coming here from Google and yah, it is rather bizarre because in the comments it says these directives will "overwrite" upstream PHP-FPM settings, which makes it sound like you can ignore them if they're already defined in `php-fpm.conf` however that is not the case.

Ref: https://github.com/php/php-src/blob/master/sapi/fpm/www.conf.in

> Additional php.ini defines, specific to this pool of workers. These settings overwrite the values previously defined in the php.ini.

Also if you're in production environment, you should keep `display_errors` disabled... here is our current [www] pool configuration for SlickStack:

https://github.com/littlebizzy/slickstack/blob/master/php-fpm/www-conf.txt

**Comment by cloudwindy** [comment]
chmod 777 would make the file executable which is unnecessary. should be 666

**Comment by ianldgs** [comment]
> chmod 777 would make the file executable which is unnecessary. should be 666

Nicely pointed. As an excuse, I can say that I just don't like the number of the beast 🤣

**Comment by mattfbacon** [comment]
Probably better to do 660 as logs can have private data. Make sure to also chown them to the user/group that php is running as.

**Comment by rahulbinari** [comment]
i got access deniend when created file 
touch: /var/log/fpm-php.www.log: Permission denied
